export const MODAL_NAMES = {
  ABOUT_CSDA: 'ABOUT_CSDA',
  ABOUT_CWIC: 'ABOUT_CWIC',
  ADVANCED_SEARCH: 'ADVANCED_SEARCH',
  CHUNKED_ORDER: 'CHUNKED_ORDER',
  DEPRECATED_PARAMETER: 'DEPRECATED_PARAMETER',
  EDIT_SUBSCRIPTION: 'EDIT_SUBSCRIPTION',
  KEYBOARD_SHORTCUTS: 'KEYBOARD_SHORTCUTS',
  OVERRIDE_TEMPORAL: 'OVERRIDE_TEMPORAL',
  RELATED_URLS: 'RELATED_URLS',
  SHAPEFILE_UPLOAD: 'SHAPEFILE_UPLOAD',
  TOO_MANY_POINTS: 'TOO_MANY_POINTS',
  VIEW_ALL_FACETS: 'VIEW_ALL_FACETS'
} as const

/** Type definitions for modal names */
export type ModalName = keyof typeof MODAL_NAMES
