FROM ruby:2.5.1
# Install dependencies
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev postgresql-client xvfb nodejs qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x cron

ENV APP_HOME /earthdata-search
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

COPY Gemfile* $APP_HOME/
COPY package*.json $APP_HOME/

RUN bundle install
RUN npm install

COPY . $APP_HOME
EXPOSE 3000
CMD bundle exec rails s -p 3000 -b '0.0.0.0'
