name: Performance Testing

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  playwright:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          node-version: ['lts/jod']
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup
      uses: ./.github/actions/npm-setup

    - name: Run Playwright tests
      run: npm run playwright:ci:performance
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        directory: 'playwright-coverage'
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ strategy.job-index }}
        path: |
          playwright-report/
          test-results/
        retention-days: 30
