name: Performance Testing

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  playwright:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          node-version: ['lts/hydrogen']
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        # not caching node_modules because `npm ci` removes it
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Copy secrets example file
      run: npm run copy-secrets
    - name: Prepare for Playwright tests
      run: npm run playwright:prepare-ci
    - name: Run Playwright tests
      run: npm run playwright:ci:performance
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        directory: 'playwright-coverage'
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ strategy.job-index }}
        path: |
          playwright-report/
          test-results/
        retention-days: 30